pr102017Videoteka/WebRole/Controllers/HomeController.cs
using FilmService_Data;
using FilmService_Data.Interfejsi;
using Microsoft.WindowsAzure.ServiceRuntime;
using System;
using System.Collections.Generic;
using System.Linq;
using System.ServiceModel;
using System.Web;
using System.Web.Mvc;

namespace WebRole.Controllers
{
    public class HomeController : Controller
    {
        private String handlerEndPoint = "InternalRequest";
        public ActionResult Index()
        {
            
                IReadFilm proxy;
                var binding = new NetTcpBinding();
                ChannelFactory<IReadFilm> factory = new
               ChannelFactory<IReadFilm>(binding, new EndpointAddress("net.tcp://localhost:6000/InputRequest"));
                proxy = factory.CreateChannel();
                ViewBag.filmovi = proxy.DobaviFilmove();
                HttpContext.Application["filmovi"] = ViewBag.filmovi;
          
            return View();
        }

        [HttpPost]
        public ActionResult Film(string naziv, string godina, string zanr)
        {
            Film f = new Film(naziv,godina, zanr);
            List<Film> filmovi =(List<Film>) HttpContext.Application["filmovi"];
           


            var binding = new NetTcpBinding();
 
            RoleInstanceEndpoint inputEndPoint = RoleEnvironment.Roles["WriterWorkerRole"].Instances[1].InstanceEndpoints[handlerEndPoint];
            string endpoint = String.Format("net.tcp://{0}/{1}", inputEndPoint.IPEndpoint, handlerEndPoint);

            ChannelFactory<IWriteFilm> factory = new ChannelFactory<IWriteFilm>(binding, endpoint);
            IWriteFilm proxy = factory.CreateChannel();

            foreach (Film item in filmovi)
            {
                if (item.RowKey == f.RowKey)
                {
                    proxy.AzurirajFilm(f);
                    return RedirectToAction("Index");

                }
            }
            proxy.UpisiFilm(f);


            return RedirectToAction("Index");




        }
        public ActionResult DeleteFilm(string naziv, string godina, string zanr)
        {
            Film f = new Film(naziv, godina, zanr);

            var binding = new NetTcpBinding();

            RoleInstanceEndpoint inputEndPoint = RoleEnvironment.Roles["WriterWorkerRole"].Instances[1].InstanceEndpoints[handlerEndPoint];
            string endpoint = String.Format("net.tcp://{0}/{1}", inputEndPoint.IPEndpoint, handlerEndPoint);

            ChannelFactory<IWriteFilm> factory = new ChannelFactory<IWriteFilm>(binding, endpoint);
            IWriteFilm proxy = factory.CreateChannel();
            proxy.ObrisiFilm(f);

            return RedirectToAction("Index");

        }
    }
}

pr102017Videoteka/WebRole/Controllers/IznajmljeniController.cs
using FilmService_Data;
using FilmService_Data.Interfejsi;
using Microsoft.WindowsAzure.ServiceRuntime;
using System;
using System.Collections.Generic;
using System.Linq;
using System.ServiceModel;
using System.Web;
using System.Web.Mvc;

namespace WebRole.Controllers
{
    public class IznajmljeniController : Controller
    {
        private String handlerEndPoint = "InternalRequest";
        public ActionResult Index()
        {
            IReadFilm proxy;
            var binding = new NetTcpBinding();
            ChannelFactory<IReadFilm> factory = new
           ChannelFactory<IReadFilm>(binding, new EndpointAddress("net.tcp://localhost:6000/InputRequest"));
            proxy = factory.CreateChannel();
            ViewBag.iznajmljeni = proxy.DobaviIznajmljene();
            HttpContext.Application["iznajmljeni"] = ViewBag.iznajmljeni;
            return View();
        }


        [HttpPost]
        public ActionResult Iznajmljen(string naziv, string ime, string br)
        {
            IznajmljeniFilm i = new IznajmljeniFilm(naziv, ime, br);
            List<IznajmljeniFilm> iz = (List<IznajmljeniFilm>)HttpContext.Application["iznajmljeni"];

            var binding = new NetTcpBinding();

            RoleInstanceEndpoint inputEndPoint = RoleEnvironment.Roles["WriterWorkerRole"].Instances[0].InstanceEndpoints[handlerEndPoint];
            string endpoint = String.Format("net.tcp://{0}/{1}", inputEndPoint.IPEndpoint, handlerEndPoint);

            ChannelFactory<IWriteFilm> factory = new ChannelFactory<IWriteFilm>(binding, endpoint);
            IWriteFilm proxy = factory.CreateChannel();
            foreach (IznajmljeniFilm item in iz)
            {
                if (item.RowKey == i.RowKey)
                {
                    proxy.AzurirajIznajmljen(i);
                    return RedirectToAction("Index");

                }
            }
            proxy.UpisiIznajmljen(i);


            return RedirectToAction("Index");
        }
        public ActionResult DeleteIznajmljen(string naziv, string ime, string br)
        {
            IznajmljeniFilm i = new IznajmljeniFilm(naziv, ime, br);


            var binding = new NetTcpBinding();

            RoleInstanceEndpoint inputEndPoint = RoleEnvironment.Roles["WriterWorkerRole"].Instances[2].InstanceEndpoints[handlerEndPoint];
            string endpoint = String.Format("net.tcp://{0}/{1}", inputEndPoint.IPEndpoint, handlerEndPoint);

            ChannelFactory<IWriteFilm> factory = new ChannelFactory<IWriteFilm>(binding, endpoint);
            IWriteFilm proxy = factory.CreateChannel();
            proxy.ObrisiIznajmljen(i);

            return RedirectToAction("Index");

        }
    }
}

pr102017Videoteka/WebRole/Controllers/KlijentController.cs
using FilmService_Data;
using FilmService_Data.Interfejsi;
using Microsoft.WindowsAzure.ServiceRuntime;
using System;
using System.Collections.Generic;
using System.Linq;
using System.ServiceModel;
using System.Web;
using System.Web.Mvc;

namespace WebRole.Controllers
{
    public class KlijentController : Controller
    {
        private String handlerEndPoint = "InternalRequest";

        public ActionResult Index()
        {
            IReadFilm proxy;
            var binding = new NetTcpBinding();
            ChannelFactory<IReadFilm> factory = new
           ChannelFactory<IReadFilm>(binding, new EndpointAddress("net.tcp://localhost:6000/InputRequest"));
            proxy = factory.CreateChannel();
            ViewBag.klijenti = proxy.DobaviKlijente();
            HttpContext.Application["klijenti"] = ViewBag.klijenti;
            return View();
        }

        [HttpPost]
        public ActionResult Klijent(string br,string ime,string prezime)
        {
            Klijent k = new Klijent(br, ime, prezime);
            List<Klijent> kl = (List<Klijent>)HttpContext.Application["klijenti"];


            var binding = new NetTcpBinding();

            RoleInstanceEndpoint inputEndPoint = RoleEnvironment.Roles["WriterWorkerRole"].Instances[1].InstanceEndpoints[handlerEndPoint];
            string endpoint = String.Format("net.tcp://{0}/{1}", inputEndPoint.IPEndpoint, handlerEndPoint);

            ChannelFactory<IWriteFilm> factory = new ChannelFactory<IWriteFilm>(binding, endpoint);
            IWriteFilm proxy = factory.CreateChannel();
            foreach (Klijent item in kl)
            {
                if (item.RowKey == k.RowKey)
                {
                    proxy.AzurirajKlijenta(k);
                    return RedirectToAction("Index");

                }
            }
            proxy.UpisiKlijenta(k);


            return RedirectToAction("Index");
        }
        public ActionResult DeleteKlijent(string br, string ime, string prezime)
        {
            Klijent k = new Klijent(br, ime, prezime);

            var binding = new NetTcpBinding();

            RoleInstanceEndpoint inputEndPoint = RoleEnvironment.Roles["WriterWorkerRole"].Instances[1].InstanceEndpoints[handlerEndPoint];
            string endpoint = String.Format("net.tcp://{0}/{1}", inputEndPoint.IPEndpoint, handlerEndPoint);

            ChannelFactory<IWriteFilm> factory = new ChannelFactory<IWriteFilm>(binding, endpoint);
            IWriteFilm proxy = factory.CreateChannel();
            proxy.ObrisiKlijenta(k);

            return RedirectToAction("Index");

        }
    }
}

pr102017Videoteka/WebRole/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

pr102017Videoteka/WebRole/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

pr102017Videoteka/WebRole/Views/Home/Index.cshtml
@using FilmService_Data
@model IEnumerable<FilmService_Data.Film>
@{
    ViewBag.Title = "Home Page";
}
<div class="container">
    <h2>Pocetna Stranica</h2>
</div>

<form action="~/Home/Film" method="post">
    <div class="form-group">
        <p>Dodaj film (Ukoliko zelite i da azurirate, ukucajte naziv filma i popunite polja i film ce biti azuriran) </p>
    </div>
    <div class="form-group">
        <label for="exampleInputPassword1">Naziv</label>
        <input type="text" class="form-control" id="exampleInputPassword1" name="naziv" required>
    </div>
    <div class="form-group">
        <label for="exampleInputPassword1">Godina</label>
        <input type="number" class="form-control" id="exampleInputPassword1" name="godina" required>
    </div>
    <div class="form-group">
        <label for="exampleInputPassword1">Zanr</label>
        <input type="number" class="form-control" id="exampleInputPassword1" name="zanr" required>
    </div>
    <button type="submit" class="btn btn-default">Submit</button>
</form>

@if(ViewBag.filmovi != null)
{
   <table class="table">
        <tr>
            <th>
                ID
            </th>
            <th>
                Godina
            </th>
        </tr>
      
       @foreach (Film item in ViewBag.filmovi)
            {
                <tr>
                    <td>
                        @item.RowKey
                    </td>
                    <td>
                        @item.Godina
                    </td>
                    <td>
                        <form action="~/Home/DeleteFilm">
                            <input type="submit" value="Izbrisi"/>
                            <input type="text" value="@item.RowKey" name="naziv" hidden /> 
                            <input type="text" value="@item.Godina" name="godina" hidden /> 
                            <input type="text" value="@item.Zanr" name="zanr" hidden /> 
                        </form>
                    </td>

           
                </tr>
            }
            
   </table>
}

pr102017Videoteka/WebRole/Views/Iznajmljeni/Index.cshtml
@using FilmService_Data

@{
    ViewBag.Title = "Index";
}

<div class="container">
    <h2>Stranica iznajmljenih filmova</h2>
</div>

<form action="~/Iznajmljeni/Iznajmljen" method="post">
    <div class="form-group">
        <p>Dodaj Iznajmljen film (Ukoliko zelite i da azurirate, ukucajte naziv filma i popunite polja i film ce biti azuriran) </p>
    </div>
    <div class="form-group">
        <label for="exampleInputPassword1">Naziv filma</label>
        <input type="text" class="form-control" id="exampleInputPassword1" name="naziv" required>
    </div>
    <div class="form-group">
        <label for="exampleInputPassword1">Ime Klijenta</label>
        <input type="text" class="form-control" id="exampleInputPassword1" name="ime" required>
    </div>
    <div class="form-group">
        <label for="exampleInputPassword1">Broj telefona</label>
        <input type="text" class="form-control" id="exampleInputPassword1" name="br" required>
    </div>
    <button type="submit" class="btn btn-default">Submit</button>
</form>

@if (ViewBag.iznajmljeni != null)
{
    <table class="table">
        <tr>
            <th>
                Naziv filma
            </th>
            <th>
                Ime klijenta
            </th>
            <th>
                Broj klijenta
            </th>
        </tr>

        @foreach (IznajmljeniFilm item in ViewBag.iznajmljeni)
        {
        <tr>
            <td>
                @item.RowKey
            </td>
            <td>
                @item.imeKlijenta
            </td>
            <td>
                @item.brojTelefonaKlijenta
            </td>
            <td>
                <form action="~/Iznajmljeni/DeleteIznajmljen">
                    <input type="submit" value="Izbrisi" />
                    <input type="text" value="@item.RowKey" name="naziv" hidden />
                    <input type="text" value="@item.imeKlijenta" name="ime" hidden />
                    <input type="text" value="@item.brojTelefonaKlijenta" name="br" hidden />
                </form>
            </td>


        </tr>
        }

    </table>
}

pr102017Videoteka/WebRole/Views/Klijent/Index.cshtml
@using FilmService_Data

@{
    ViewBag.Title = "Index";
}

<div class="container">
    <h2>Stranica klijenata</h2>
</div>

<form action="~/Klijent/Klijent" method="post">
    <div class="form-group">
        <p>Dodaj Klijenta (Ukoliko zelite i da azurirate, ukucajte broj klijneta i popunite polja i klijent ce biti azuriran) </p>
    </div>
    <div class="form-group">
        <label for="exampleInputPassword1">Broj telefona</label>
        <input type="text" class="form-control" id="exampleInputPassword1" name="br" required>
    </div>
    <div class="form-group">
        <label for="exampleInputPassword1">Ime</label>
        <input type="text" class="form-control" id="exampleInputPassword1" name="ime" required>
    </div>
    <div class="form-group">
        <label for="exampleInputPassword1">Prezime</label>
        <input type="text" class="form-control" id="exampleInputPassword1" name="prezime" required>
    </div>
    <button type="submit" class="btn btn-default">Submit</button>
</form>

@if (ViewBag.klijenti != null)
{
    <table class="table">
        <tr>
            <th>
                Broj Telefona
            </th>
            <th>
                Ime
            </th>
        </tr>

        @foreach (Klijent item in ViewBag.klijenti)
        {
            <tr>
                <td>
                    @item.RowKey
                </td>
                <td>
                    @item.ime
                </td>
                <td>
                    <form action="~/Klijent/DeleteKlijent">
                        <input type="submit" value="Izbrisi" />
                        <input type="text" value="@item.RowKey" name="br" hidden />
                        <input type="text" value="@item.ime" name="ime" hidden />
                        <input type="text" value="@item.prezime" name="prezime" hidden />
                    </form>
                </td>


            </tr>
        }

    </table>
}

pr102017Videoteka/WebRole/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Klijenti", "Index", "Klijent")</li>
                    <li>@Html.ActionLink("Iznajmljeni Filmovi", "Index", "Iznajmljeni")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>